version: '3.1'

services:
  redis:
    image: 'redis:3.2.7'
    restart: always

  postgres:
    image: postgres:9.6
    restart: always

    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - AIRFLOW__WEBSERVER__WORKERS=2
      - AIRFLOW__CELERY__WORKER_CONCURRENCY=16
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAG_CONCURRENCY=32
      - AIRFLOW__CORE__PARALLELISM=64
      - AIRFLOW__CORE__SQL_ALCHEMY_POOL_RECYCLE=3600
      - AIRFLOW__CORE__SQL_ALCHEMY_POOL_SIZE=100
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
      - ./sql:/usr/local/airflow/sql
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
    environment:
      - EXECUTOR=Celery
      - AIRFLOW__WEBSERVER__WORKERS=2
      - AIRFLOW__CELERY__WORKER_CONCURRENCY=16
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAG_CONCURRENCY=32
      - AIRFLOW__CORE__PARALLELISM=64
      - AIRFLOW__CORE__SQL_ALCHEMY_POOL_RECYCLE=3600
      - AIRFLOW__CORE__SQL_ALCHEMY_POOL_SIZE=100
    volumes:
      - ./req.txt:/req.txt
    ports:
      - "5555:5555"
    command: flower

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - webserver
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
      - ./sql:/usr/local/airflow/sql
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - AIRFLOW__WEBSERVER__WORKERS=2
      - AIRFLOW__CELERY__WORKER_CONCURRENCY=16
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAG_CONCURRENCY=32
      - AIRFLOW__CORE__PARALLELISM=64
      - AIRFLOW__CORE__SQL_ALCHEMY_POOL_RECYCLE=3600
      - AIRFLOW__CORE__SQL_ALCHEMY_POOL_SIZE=100
    command: scheduler

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - scheduler
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
      - ./sql:/usr/local/airflow/sql
    environment:
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - AIRFLOW__WEBSERVER__WORKERS=2
      - AIRFLOW__CELERY__WORKER_CONCURRENCY=16
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAG_CONCURRENCY=32
      - AIRFLOW__CORE__PARALLELISM=64
      - AIRFLOW__CORE__SQL_ALCHEMY_POOL_RECYCLE=3600
      - AIRFLOW__CORE__SQL_ALCHEMY_POOL_SIZE=100
    command: worker